lista_nomes_restaurantes= []
lista_tipos_restaurantes = []
lista_cnpj_restaurantes = []
lista_telefone_restaurantes = []
lista_email_restaurantes = []
lista_endereco_restaurantes = []

opcao_sim_nao = ['Sim', 'S', 'NAO', 'N']
opcao_tipo_cadastro = ['Pessoa', 'P', 'Restaurante', 'R']
opcao_menu = ['1', '2', '3', '4']